services:
  telegram-signal-bridge:
    platform: linux/arm64/v8
    build:
      context: .
      args:
        BUILD_ENV: prod
    image: '${DOCKER_IMAGE_PROD}:0.0.3-alpine-arm64'
    command: ["-t", "10"]
    volumes:
      - ${SIGNALCLI_CONFIG_VOL}:/home/node/.local/share/signal-cli
