services:
  telegram-signal-bridge:
    platform: linux/arm64/v8
    build:
      context: .
      args:
        BUILD_ENV: dev
    image: 'telegram-signal-bridge:0.0.3-alpine-arm64'
    command: ["-t", "20"]
    volumes:
      - .:/telegram-signal-bridge
      - ${SIGNALCLI_CONFIG_VOL}:/home/node/.local/share/signal-cli
