services:
  telegram-signal-bridge:
    build:
      context: .
      args:
        BUILD_ENV: dev
    image: 'telegram-signal-bridge:0.0.3-alpine'
    command: ["-t", "10"]
    volumes:
      - .:/telegram-signal-bridge
      - ${SIGNALCLI_CONFIG_VOL}:/home/node/.local/share/signal-cli
